@startuml

class "Версия офиса" as OfficeVersion {
	{field} *version_id : int
	..
	{field} *name : str
}

class "Ключ офиса" as OfficeKey {
	{field} *key_id : int
	..
	{field} *office_version_id : int
	{field} *key_text : str
	{field} note : str
}

class "Версия ОС" as OSVersion {
	{field} *version_id : int
	..
	{field} *name : str
}

class "Ключ ОС" as OSKey {
	{field} *key_id : int
	..
	{field} *os_version_id : int
	{field} *key_text : str
	{field} note : str
}

class "Подразделение" as Division {
	{field} *division_id : int
	..
	{field} *name : str
}

class "Рабочее место" as WorkPlace {
	{field} *workplace_id : int
	..
	{field} *division_id : int
	{field} *name : str
	{field} *computer_id : int
	{field} *monitor_id : int
	{field} username_id : int
	{field} note : str
} 

class "Компьютер" as Computer {
	{field} *computer_id : int
	..
	{field} *inventory_number : str
	{field} *name : str
	{field} *responsible_id : int
	{field} *proccessor_id : int
	{field} *hdd_id : int
	{field} *ram_id : int
	{field} *motherboard_id : int
	{field} videocard_id : int
	{field} *os_key_id : int
	{field} *os_bit_depth : str
	{field} office_key_id : int
	{field} *ip_address : str
	{field} note : str
}	

class "История компьютера" as ComputerHistory {
	{field} *change_date : date
}

class "Монитор" as Monitor {
	{field} *monitor_id : int
	..
	{field} *model_id : int
	{field} *serial_no : str
}

class "Учетные записи" as UserName {
	{field} *username_id : int
	..
	{field} *name : str
	{field} fio : str
	{field} password : str
}

class "Ответственное лицо" as Responsible {
	{field} *responsible_id : int
	..
	{field} *fio : str
} 
		
class "Производитель" as Manufacturer {
	{field} *manufacturer_id : int
	..
	{field} *name : str
}

abstract class "Модель комплектующего" as AbstractAccessoryModel {
	{field} *model_id : int
	..
	{field} *manufacturer_id : int
	{field} *model : str
}

class "Тип ОЗУ" as RAMType {
	{field} *ramtype_id : int
	..
	{field} *name : str
}

class "Объем памяти" as MemoryCapacity {
	{field} *memorycapacity_id : int
	..
	{field} *capacity : str	
}

class "Модель ОЗУ" as RAMModel {
	{field} *ramtype_id : int
	{field} capacity_id : int
}

class "ОЗУ" as RAM {
	{field} *ram_id : int
	..
	{field} *model_id : int
	{field} *serial_no : str
}

class "Класс HDD" as HDDType {
	{field} *hddtype_id : int
	..
	{field} *name : str
}

class "Модель HDD" as HDDModel {
	{field} *hddtype_id : int
	{field} *capacity_id : int	
}

class "HDD" as HDD {
	{field} *hdd_id : int
	..
	{field} *model_id : int
	{field} *serial_no : str
}


class "Модель монитора" as MonitorModel {
}		

class "Модель материнки" as MotherboardModel {
}

class "Материнка" as Motherboard {
	{field} *motherboard_id : int
	..
	{field} *model_id : int
	{field} serial_no : str
}

class "Модель видео карты" as VideocardModel {
}

class "Видеокарта" as Videocard {
	{field} *videocard_id : int
	..
	{field} *model_id : int
	{field} serial_no : str
}

class "Модель процессора" as ProcessorModel {
}

class "Процессор" as Processor {
	{field} *processor_id : int
	..
	{field} *model_id : int
	{field} serial_no : str
}

OfficeKey }-- OfficeVersion
OSKey }-- OSVersion
WorkPlace }-- Division	
Computer -- OSKey
Computer -- OfficeKey
Computer o-- WorkPlace	
Computer }-- Responsible
ComputerHistory --|> Computer
AbstractAccessoryModel }-- Manufacturer
MonitorModel --|> AbstractAccessoryModel		
Monitor o-- WorkPlace
Monitor }-- MonitorModel
UserName -- WorkPlace
RAMModel }-- RAMType
RAMModel }-- MemoryCapacity
RAMModel --|> AbstractAccessoryModel
RAM }-- RAMModel
RAM }-- Computer
HDDModel }-- HDDType
HDD }-- Computer	
HDDModel --|> AbstractAccessoryModel
HDDModel }-- MemoryCapacity
HDD }-- HDDModel	
MotherboardModel --|> AbstractAccessoryModel
Motherboard }-- MotherboardModel
Motherboard -- Computer		
VideocardModel --|> AbstractAccessoryModel
Videocard }-- VideocardModel
Videocard o-- Computer		
ProcessorModel --|> AbstractAccessoryModel
Processor }-- ProcessorModel
Processor -- Computer

@enduml
