@startuml

class "Версия офиса" as OfficeVersion {
	{field} *version_id : int
	..
	{field} *name : str
}

class "Ключ офиса" as OfficeKey {
	{field} *key_id : int
	..
	{field} *office_version_id : int
	{field} *key_text : str
	{field} note : str
}

class "Версия ОС" as OSVersion {
	{field} *version_id : int
	..
	{field} *name : str
}

class "Ключ ОС" as OSKey {
	{field} *key_id : int
	..
	{field} *os_version_id : int
	{field} *key_text : str
	{field} note : str
}

class "Подразделение" as Division {
	{field} *division_id : int
	..
	{field} *name : str
}

class "Рабочее место" as WorkPlace {
	{field} *workplace_id : int
	..
	{field} *division_id : int
	{field} *name : str
	{field} *computer_id : int
	{field} *monitor_id : int
	{field} username_id : int
	{field} note : str
} 

class "Компьютер" as Computer {
	{field} *computer_id : int
	..
	{field} *inventory_number : str
	{field} *name : str
	{field} *responsible_id : int
	{field} *proccessor : str
	{field} *os_key_id : int
	{field} *os_bit_depth : str
	{field} *ram_capacity : int
	{field} *has_ssd : bool
	{field} office_key_id : int
	{field} *ip_address : str
	{field} note : str
}	

class "История компьютера" as ComputerHistory {
	{field} *change_date : date
}

class "Монитор" as Monitor {
	{field} *monitor_id : int
	..
	{field} *name : str
	{field} *serial_no : str
}

class "Учетные записи" as UserName {
	{field} *username_id : int
	..
	{field} *name : str
	{field} fio : str
	{field} password : str
}

class "Ответственное лицо" as Responsible {
	{field} *responsible_id : int
	..
	{field} *fio : str
} 
		
class "Производитель" as Manufacturer {
	{field} *manufacturer_id : int
	..
	{field} *name : str
}

class "Тип ОЗУ" as RAMType {
	{field} *ramtype_id : int
	..
	{field} *name : str
}

class "Объем памяти" as MemoryCapacity {
	{field} *memorycapacity_id : int
	..
	{field} *capacity : str	
}

class "ОЗУ" as RAM {
	{field} *ram_id : int
	..
	{field} *manufacturer_id : int
	{field} *ramtype_id : int
	{field} capacity_id : int
	{field} *serial_no : str
	{field} computer_id : int
}

class "Класс HDD" as HDDType {
	{field} *hddtype_id : int
	..
	{field} *name : str
}

class "HDD" as HDD {
	{field} *hdd_id : int
	..
	{field} hddtype_id : int
	{field} manufacturer_id : int
	{field} *model : int
	{field} capacity_id : int
	{field} computer_id : int
}


OfficeKey }-- OfficeVersion
OSKey }-- OSVersion
WorkPlace }-- Division	
Computer -- OSKey
Computer -- OfficeKey
Computer o-- WorkPlace	
Computer }-- Responsible
ComputerHistory --|> Computer
Monitor o-- WorkPlace
Monitor }-- Manufacturer
UserName -- WorkPlace
RAM }-- RAMType
RAM }-- MemoryCapacity
RAM }-- Manufacturer
RAM }-- Computer
HDD }-- HDDType
HDD }-- Computer	
HDD }-- Manufacturer

@enduml
