# docker-compose.yml

version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    env_file: .env
    build:
      context: ./ipce/
      dockerfile: Dockerfile.local
    volumes:
      - static:/backend_static
    depends_on:
      - db

  gateway:
    build: ./gateway/
    ports:
      - 8000:80
    volumes:
      - static:/static/
