# Generated by Django 4.2.3 on 2023-08-02 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "office version",
                "verbose_name_plural": "office versions",
            },
        ),
        migrations.CreateModel(
            name="OSVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "OS version",
                "verbose_name_plural": "OS versions",
            },
        ),
        migrations.CreateModel(
            name="OSKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_text",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="invalid key format",
                                regex="[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}",
                            )
                        ],
                        verbose_name="key",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "os_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="software.osversion",
                        verbose_name="OS version",
                    ),
                ),
            ],
            options={
                "verbose_name": "OS key",
                "verbose_name_plural": "OS keys",
            },
        ),
        migrations.CreateModel(
            name="OfficeKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_text",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="invalid key format",
                                regex="[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}",
                            )
                        ],
                        verbose_name="key",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "office_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="software.officeversion",
                        verbose_name="office version",
                    ),
                ),
            ],
            options={
                "verbose_name": "office key",
                "verbose_name_plural": "office keys",
            },
        ),
        migrations.AddConstraint(
            model_name="oskey",
            constraint=models.UniqueConstraint(
                fields=("os_version", "key_text"), name="OS_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="officekey",
            constraint=models.UniqueConstraint(
                fields=("office_version", "key_text"), name="office_key_unique"
            ),
        ),
    ]
