# Generated by Django 4.2.3 on 2023-10-02 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0002_alter_officekey_options_alter_oskey_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officeversion",
            options={
                "ordering": ("name",),
                "verbose_name": "office version",
                "verbose_name_plural": "office versions",
            },
        ),
        migrations.AlterModelOptions(
            name="osversion",
            options={
                "ordering": ("name",),
                "verbose_name": "OS version",
                "verbose_name_plural": "OS versions",
            },
        ),
    ]
