## -*- dockerfile-image-name: backend -*-

FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN python -m pip install --upgrade pip
RUN pip install -r ./requirements/requirements.txt --no-cache-dir
# RUN pip install -r requirements/requirements.local.txt --no-cache-dir
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "ipce.wsgi"]
