# Generated by Django 4.2.3 on 2023-07-27 13:39

import computers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "office version",
                "verbose_name_plural": "office versions",
            },
        ),
        migrations.CreateModel(
            name="OfficeKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_text",
                    models.CharField(
                        max_length=40,
                        validators=[computers.validators.validate_office_key],
                        verbose_name="key",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "office_version_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="computers.officeversion",
                        verbose_name="version id",
                    ),
                ),
            ],
            options={
                "verbose_name": "office key",
                "verbose_name_plural": "office keys",
            },
        ),
    ]
