# Generated by Django 4.2.3 on 2023-08-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="inventory number"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=20, verbose_name="name"),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="processor"
                    ),
                ),
                (
                    "os_bit_depth",
                    models.CharField(
                        blank=True,
                        choices=[(None, "Unknown"), ("x32", "X32"), ("x64", "X64")],
                        max_length=3,
                        verbose_name="OS bit depth",
                    ),
                ),
                ("has_ssd", models.BooleanField(default=False, verbose_name="has SSD")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        protocol="IPv4",
                        unique=True,
                        verbose_name="IP address",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "office_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="software.officekey",
                        verbose_name="office key",
                    ),
                ),
                (
                    "os_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="software.oskey",
                        verbose_name="OS key",
                    ),
                ),
            ],
            options={
                "verbose_name": "computer",
                "verbose_name_plural": "computers",
                "default_related_name": "computer",
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "division",
                "verbose_name_plural": "divisions",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MemoryCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="capacity"
                    ),
                ),
            ],
            options={
                "verbose_name": "memory capacity",
                "verbose_name_plural": "memory capacities",
                "ordering": ("capacity",),
            },
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="model")),
                (
                    "serial_no",
                    models.CharField(max_length=50, verbose_name="serial number"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="monitor",
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitor",
                "verbose_name_plural": "monitors",
                "default_related_name": "monitor",
            },
        ),
        migrations.CreateModel(
            name="RAMType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="RAM type"
                    ),
                ),
            ],
            options={
                "verbose_name": "RAM type",
                "verbose_name_plural": "RAM types",
            },
        ),
        migrations.CreateModel(
            name="Responsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="FIO")),
            ],
            options={
                "verbose_name": "responsible",
                "verbose_name_plural": "responsibles",
            },
        ),
        migrations.CreateModel(
            name="UserName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "fio",
                    models.CharField(blank=True, max_length=255, verbose_name="FIO"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="password"
                    ),
                ),
            ],
            options={
                "verbose_name": "username",
                "verbose_name_plural": "usernames",
            },
        ),
        migrations.CreateModel(
            name="WorkPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.division",
                        verbose_name="division",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.monitor",
                        verbose_name="monitor",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.username",
                        verbose_name="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "work place",
                "verbose_name_plural": "work places",
                "default_related_name": "workplace",
            },
        ),
        migrations.CreateModel(
            name="WorkplaceComputerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_date", models.DateField(verbose_name="install date")),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_history",
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computer_history",
                        to="computers.workplace",
                        verbose_name="work place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workplace computers",
                "verbose_name_plural": "workplaces computers",
            },
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="serial number"
                    ),
                ),
                (
                    "capacity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.memorycapacity",
                        verbose_name="memory capacity",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
                (
                    "ram_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.ramtype",
                        verbose_name="RAM type",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAM",
                "verbose_name_plural": "RAM",
                "default_related_name": "ram",
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="responsible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.responsible",
                verbose_name="responsible",
            ),
        ),
        migrations.AddConstraint(
            model_name="workplacecomputerhistory",
            constraint=models.UniqueConstraint(
                fields=("workplace", "computer", "install_date"),
                name="unique_workplace_computer_history",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitor",
            constraint=models.UniqueConstraint(
                fields=("name", "serial_no"), name="unique_monitor_name_serial_no"
            ),
        ),
    ]
