# Generated by Django 4.2.3 on 2023-07-28 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import computers.validators


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "division",
                "verbose_name_plural": "divisions",
            },
        ),
        migrations.CreateModel(
            name="OSVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "OS version",
                "verbose_name_plural": "OS versions",
            },
        ),
        migrations.RemoveField(
            model_name="officekey",
            name="office_version_id",
        ),
        migrations.AddField(
            model_name="officekey",
            name="office_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="computers.officeversion",
                verbose_name="office version",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WorkPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("note", models.TextField(verbose_name="note")),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workplaces",
                        to="computers.division",
                        verbose_name="division",
                    ),
                ),
            ],
            options={
                "verbose_name": "work place",
                "verbose_name_plural": "work places",
            },
        ),
        migrations.CreateModel(
            name="OSKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_text",
                    models.CharField(
                        max_length=40,
                        validators=[computers.validators.validate_os_key],
                        verbose_name="key",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "os_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="computers.osversion",
                        verbose_name="OS version",
                    ),
                ),
            ],
            options={
                "verbose_name": "OS key",
                "verbose_name_plural": "OS keys",
            },
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=10, verbose_name="inventory number"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "os_bit_depth",
                    models.IntegerField(
                        verbose_name="OS bit depth",
                    ),
                ),
                (
                    "ram_capacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "negative RAM capacity"
                            )
                        ],
                        verbose_name="RAM capacity",
                    ),
                ),
                ("has_ssd", models.BooleanField(default=False, verbose_name="has SSD")),
                ("user", models.CharField(max_length=150, verbose_name="user")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        protocol="IPv4",
                        verbose_name="IP address",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "office_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.officekey",
                        verbose_name="office key",
                    ),
                ),
                (
                    "os_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.oskey",
                        verbose_name="OS key",
                    ),
                ),
                (
                    "work_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.workplace",
                        verbose_name="work place",
                    ),
                ),
            ],
            options={
                "verbose_name": "computer",
                "verbose_name_plural": "computers",
                "default_related_name": "computer",
            },
        ),
    ]
