# Generated by Django 4.2.3 on 2023-08-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HDDType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "hdd type",
                "verbose_name_plural": "hdd types",
            },
        ),
        migrations.CreateModel(
            name="HDD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(max_length=255, verbose_name="serial number"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                (
                    "capacity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.memorycapacity",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "hdd_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.hddtype",
                        verbose_name="hdd type",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDD",
                "verbose_name_plural": "HDDs",
                "default_related_name": "hdd",
            },
        ),
    ]
