# Generated by Django 4.2.3 on 2023-07-28 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0002_division_osversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oskey",
            name="key_text",
            field=models.CharField(
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid key format",
                        regex="[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}-[\\d\\w]{5}",
                    )
                ],
                verbose_name="key",
            ),
        ),
    ]
