# Generated by Django 4.2.3 on 2023-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0003_alter_oskey_key_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="inventory_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="inventory number"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="name",
            field=models.CharField(blank=True, max_length=20, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="user",
            field=models.CharField(blank=True, max_length=150, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="officekey",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="oskey",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
    ]
