# Generated by Django 4.2.3 on 2023-08-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0003_remove_computer_has_ssd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ram",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="ram",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="ram",
            name="ram_type",
        ),
        migrations.CreateModel(
            name="RAMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.memorycapacity",
                        verbose_name="memory capacity",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
                (
                    "ram_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.ramtype",
                        verbose_name="RAM type",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAM model",
                "verbose_name_plural": "RAM models",
                "default_related_name": "ram_model",
            },
        ),
        migrations.AddField(
            model_name="ram",
            name="ram_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.rammodel",
                verbose_name="RAM model",
            ),
            preserve_default=False,
        ),
    ]
