# Generated by Django 4.2.3 on 2023-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "computers",
            "0004_alter_computer_inventory_number_alter_computer_name_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="officekey",
            constraint=models.UniqueConstraint(
                fields=("office_version", "key_text"), name="office_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="oskey",
            constraint=models.UniqueConstraint(
                fields=("os_version", "key_text"), name="OS_key_unique"
            ),
        ),
    ]
