# Generated by Django 4.2.3 on 2023-08-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0004_remove_ram_capacity_remove_ram_manufacturer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hdd",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="hdd",
            name="hdd_type",
        ),
        migrations.RemoveField(
            model_name="hdd",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="hdd",
            name="model",
        ),
        migrations.CreateModel(
            name="HDDModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                (
                    "capacity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.memorycapacity",
                    ),
                ),
                (
                    "hdd_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.hddtype",
                        verbose_name="hdd type",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDD model",
                "verbose_name_plural": "HDD models",
            },
        ),
        migrations.AddField(
            model_name="hdd",
            name="hdd_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.hddmodel",
                verbose_name="HDD model",
            ),
            preserve_default=False,
        ),
    ]
