# Generated by Django 4.2.3 on 2023-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0005_officekey_office_key_unique_oskey_os_key_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="processor",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="processor"
            ),
        ),
    ]
