# Generated by Django 4.2.3 on 2023-08-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0005_remove_hdd_capacity_remove_hdd_hdd_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hdd",
            name="computer",
        ),
        migrations.AlterField(
            model_name="ram",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.computer",
                verbose_name="hdd",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ComputerHDD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="hdd",
                    ),
                ),
                (
                    "hdd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.hdd",
                        verbose_name="computer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="hdd",
            field=models.ManyToManyField(
                through="computers.ComputerHDD", to="computers.hdd", verbose_name="HDD"
            ),
        ),
        migrations.AddConstraint(
            model_name="computerhdd",
            constraint=models.UniqueConstraint(fields=("hdd",), name="unique_hdd"),
        ),
    ]
