# Generated by Django 4.2.3 on 2023-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0006_computer_processor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="os_bit_depth",
            field=models.CharField(
                blank=True,
                choices=[(None, "Unknown"), ("x32", "X32"), ("x64", "X64")],
                max_length=3,
                verbose_name="OS bit depth",
            ),
        ),
    ]
