# Generated by Django 4.2.3 on 2023-08-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "computers",
            "0006_remove_hdd_computer_alter_ram_computer_computerhdd_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ram",
            name="computer",
        ),
        migrations.AlterField(
            model_name="computerhdd",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.computer",
                verbose_name="computer",
            ),
        ),
        migrations.AlterField(
            model_name="computerhdd",
            name="hdd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.hdd",
                verbose_name="hdd",
            ),
        ),
        migrations.CreateModel(
            name="ComputerRAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "ram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.ram",
                        verbose_name="ram",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computer",
            name="ram",
            field=models.ManyToManyField(
                through="computers.ComputerRAM", to="computers.ram", verbose_name="RAM"
            ),
        ),
        migrations.AddConstraint(
            model_name="computerram",
            constraint=models.UniqueConstraint(fields=("ram",), name="unique_ram"),
        ),
    ]
