# Generated by Django 4.2.3 on 2023-08-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0007_remove_ram_computer_alter_computerhdd_computer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="name",
        ),
        migrations.AlterField(
            model_name="computerhdd",
            name="hdd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.hdd",
                verbose_name="HDD",
            ),
        ),
        migrations.AlterField(
            model_name="computerram",
            name="ram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.ram",
                verbose_name="RAM",
            ),
        ),
        migrations.CreateModel(
            name="MonitorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="model")),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitor model",
                "verbose_name_plural": "monitor models",
            },
        ),
        migrations.AddField(
            model_name="monitor",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.monitormodel",
                verbose_name="model",
            ),
            preserve_default=False,
        ),
    ]
