# Generated by Django 4.2.3 on 2023-07-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0008_alter_computer_ip_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="monitor")),
                (
                    "serial_no",
                    models.CharField(max_length=50, verbose_name="serial number"),
                ),
                (
                    "work_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computers.workplace",
                        verbose_name="work place",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitor",
                "verbose_name_plural": "monitors",
                "default_related_name": "monitor",
            },
        ),
        migrations.AddConstraint(
            model_name="monitor",
            constraint=models.UniqueConstraint(
                fields=("name", "serial_no"), name="unique_monitor_name_serial_no"
            ),
        ),
    ]
