# Generated by Django 4.2.3 on 2023-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0010_username_computer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="username",
            name="fio",
            field=models.CharField(blank=True, max_length=255, verbose_name="FIO"),
        ),
    ]
