# Generated by Django 4.2.3 on 2023-08-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0010_rammodel_model_alter_hddmodel_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="model")),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "video card model",
                "verbose_name_plural": "video card models",
            },
        ),
        migrations.CreateModel(
            name="VideoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(max_length=255, verbose_name="serial number"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cards",
                        to="computers.videocardmodel",
                        verbose_name="model",
                    ),
                ),
            ],
            options={
                "verbose_name": "video card",
                "verbose_name_plural": "video cards",
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="videocard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.videocard",
                verbose_name="video card",
            ),
        ),
    ]
