# Generated by Django 4.2.3 on 2023-07-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0011_username_fio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="FIO")),
            ],
            options={
                "verbose_name": "responsible",
                "verbose_name_plural": "responsibles",
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="responsible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.responsible",
                verbose_name="responsible",
            ),
            preserve_default=False,
        ),
    ]
