# Generated by Django 4.2.3 on 2023-07-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0012_responsible_computer_responsible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "default_related_name": "workplace",
                "verbose_name": "work place",
                "verbose_name_plural": "work places",
            },
        ),
        migrations.RemoveField(
            model_name="computer",
            name="work_place",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="work_place",
        ),
        migrations.AddField(
            model_name="workplace",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.computer",
                verbose_name="computer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workplace",
            name="monitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="computers.monitor",
                verbose_name="monitor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workplace",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="computers.division",
                verbose_name="division",
            ),
        ),
    ]
