# Generated by Django 4.2.3 on 2023-07-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "computers",
            "0013_alter_workplace_options_remove_computer_work_place_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="username",
        ),
        migrations.AddField(
            model_name="workplace",
            name="username",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="computers.username",
                verbose_name="username",
            ),
        ),
    ]
