# Generated by Django 4.2.3 on 2023-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0015_workplacecomputerhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
    ]
