# Generated by Django 4.2.3 on 2023-08-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("computers", "0017_monitor_manufacturer_alter_monitor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAMType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="RAM type"
                    ),
                ),
            ],
            options={
                "verbose_name": "RAM type",
                "verbose_name_plural": "RAM types",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("name",),
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
        migrations.RemoveField(
            model_name="computer",
            name="ram_capacity",
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        choices=[
                            (None, "Unknown"),
                            (1, "1 GB"),
                            (2, "2 GB"),
                            (4, "4 GB"),
                            (8, "8 GB"),
                            (16, "16 GB"),
                            (32, "32 GB"),
                            (64, "64 GB"),
                            (128, "128 GB"),
                            (256, "256 GB"),
                            (512, "512 GB"),
                            (1024, "1 TB"),
                            (2048, "2 TB"),
                            (4096, "4 TB"),
                        ],
                        verbose_name="RAM capacity",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="serial number"
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.computer",
                        verbose_name="computer",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.manufacturer",
                        verbose_name="manufacturer",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="computers.ramtype",
                        verbose_name="RAM type",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAM",
                "verbose_name_plural": "RAM",
                "default_related_name": "ram",
            },
        ),
    ]
